# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ap_date', models.DateTimeField()),
                ('ap_type', models.CharField(blank=True, choices=[('V', 'Vaccination'), ('F', 'Follow Up'), ('C', 'Check Up')], default='V', max_length=2, null=True)),
                ('ap_status', models.CharField(blank=True, choices=[('P', 'Planned'), ('S', 'Postponed'), ('C', 'Cancelled'), ('A', 'Attended')], default='P', max_length=2, null=True)),
                ('ap_report', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('national_id', models.CharField(max_length=11, unique=True)),
                ('MRN', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('file_no', models.CharField(blank=True, max_length=11, null=True)),
                ('nationality', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=2)),
                ('birth_date', models.DateTimeField()),
                ('status', models.CharField(blank=True, max_length=2, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mother',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('national_id', models.CharField(max_length=11)),
                ('mobile', models.CharField(max_length=12)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('motnh', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='child',
            name='mother',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vax.Mother'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vax.Child'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='vaccine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vax.Vaccine'),
        ),
    ]
