# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vax', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccine',
            old_name='motnh',
            new_name='month',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='ap_report',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='status',
            field=models.CharField(blank=True, choices=[('AC', 'Active'), ('DC', 'Deceased'), ('DI', 'Disabled')], max_length=2, null=True),
        ),
    ]
