# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vax', '0002_auto_20161231_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='ap_report',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='vaccine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vax.Vaccine'),
        ),
    ]
