# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vax', '0003_auto_20161231_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='birth_date',
            field=models.DateField(),
        ),
    ]
